"""Test data for pion_power_api client tests."""

import random
import string
import typing as t


def generate_random_string(n: int) -> str:
    """Generate a random string of length n."""
    # Combine lowercase, uppercase, and digits
    characters = string.ascii_letters + string.digits
    return "".join(random.choices(characters, k=n))  # noqa: S311


__device_one: dict[str, t.Any] = {
    "MaximumCurrent": 32.0,
    "SoftwareVersion": "2.1.5",
    "HardwareVersion": "1.0.5",
    "LastVersion": None,
    "RunStatus": 2,
    "RunStatusName": "Idle",
    "GunStatus": 1,
    "GunStatusName": "Plug-in",
    "PlugAndChargeEn": False,
    "ChargeCurrent": 6,
    "DeviceNowTime": "2026-05-02 15:02:08",
    "OnLineStatus": 1,
    "OnLineStatusName": "Online",
    "DeviceShareStatus": 2,
    "ProductCode": "55-2",
    "ProductName": "EFAC32NA11-BLE",
    "Picture": "06ProductPicture/eaa2bd8c925b4af59800bf1395f152aa.png",
    "Id": 2830,
    "DeviceId": "EFAC32NA11-" + generate_random_string(14),
    "DeviceName": "Garage Charger",
    "DeviceType": 901,
    "DeviceTypeName": "充电桩",
    "DeviceCode": "EFAC32NA11-" + generate_random_string(14),
    "StationCode": generate_random_string(18),
    "ParentCode": None,
    "SupplierCode": "0000",
    "InstallerCode": None,
    "ProductId": "d5b7aa1a-57d0-4873-bca3-50404fa273c7",
    "TimeDifference": -240,
    "TimeDifferenceType": 1,
    "ReserveA": "America/New_York",
    "ReserveB": None,
    "RatedPower": 0.0,
    "Capacity": 0.0,
    "RegisterTime": "2026-04-16 16:39:47",
    "UpdateTime": "2026-04-16 12:39:54",
}

__device_two: dict[str, t.Any] = {
    "MaximumCurrent": 32.0,
    "SoftwareVersion": "2.1.5",
    "HardwareVersion": "1.0.5",
    "LastVersion": None,
    "RunStatus": 2,
    "RunStatusName": "Idle",
    "GunStatus": 1,
    "GunStatusName": "Plug-in",
    "PlugAndChargeEn": False,
    "ChargeCurrent": 6,
    "DeviceNowTime": "2026-05-02 15:02:08",
    "OnLineStatus": 1,
    "OnLineStatusName": "Online",
    "DeviceShareStatus": 2,
    "ProductCode": "55-2",
    "ProductName": "EFAC32NA11-BLE",
    "Picture": "06ProductPicture/eaa2bd8c925b4af59800bf1395f152aa.png",
    "Id": 2830,
    "DeviceId": "EFAC32NA11-" + generate_random_string(14),
    "DeviceName": "Workshop Charger",
    "DeviceType": 901,
    "DeviceTypeName": "充电桩",
    "DeviceCode": "EFAC32NA11-" + generate_random_string(14),
    "StationCode": generate_random_string(18),
    "ParentCode": None,
    "SupplierCode": "0000",
    "InstallerCode": None,
    "ProductId": "d5b7aa1a-57d0-4873-bca3-50404fa273c7",
    "TimeDifference": -240,
    "TimeDifferenceType": 1,
    "ReserveA": "America/New_York",
    "ReserveB": None,
    "RatedPower": 0.0,
    "Capacity": 0.0,
    "RegisterTime": "2026-04-16 16:39:47",
    "UpdateTime": "2026-04-16 12:39:54",
}

__device_stats: dict[str, t.Any] = {
    "DayStat": {
        "Charge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "Discharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveCharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "PVDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "StationUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridOut": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "EVCharge": {"Value": 1.9, "Percent": 0.0, "Unit": "kWh"},
        "EVOrderNumber": 1,
        "EVChargeHours": {"Value": 0.2, "Percent": 0.0, "Unit": "h"},
        "Profit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "ESProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "PVProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
    },
    "MonthStat": {
        "Charge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "Discharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveCharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "PVDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "StationUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridOut": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "EVCharge": {"Value": 1.9, "Percent": 0.0, "Unit": "kWh"},
        "EVOrderNumber": 1,
        "EVChargeHours": {"Value": 0.2, "Percent": 0.0, "Unit": "h"},
        "Profit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "ESProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "PVProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
    },
    "YearStat": {
        "Charge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "Discharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveCharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "PVDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "StationUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridOut": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "EVCharge": {"Value": 29.3, "Percent": 0.0, "Unit": "kWh"},
        "EVOrderNumber": 5,
        "EVChargeHours": {"Value": 3.9, "Percent": 0.0, "Unit": "h"},
        "Profit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "ESProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "PVProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
    },
    "TotalStat": {
        "Charge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "Discharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveCharge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "MoveDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "PVDischarge": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "StationUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridUse": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "GridOut": {"Value": 0.0, "Percent": 0.0, "Unit": "kWh"},
        "EVCharge": {"Value": 29.3, "Percent": 0.0, "Unit": "kWh"},
        "EVOrderNumber": 5,
        "EVChargeHours": {"Value": 3.9, "Percent": 0.0, "Unit": "h"},
        "Profit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "ESProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
        "PVProfit": {"Value": 0.0, "Percent": 0.0, "Unit": ""},
    },
}

__device_data: dict[str, t.Any] = {
    "90100000": {
        "SignalId": 90100000,
        "SignalName": "Communication status",
        "SignalValue": 1.0,
        "SignalMeaning": "Online",
        "SignalUnit": "",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100002": {
        "SignalId": 90100002,
        "SignalName": "Gun plugin status",
        "SignalValue": 1.0,
        "SignalMeaning": "Plug-in",
        "SignalUnit": "",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100006": {
        "SignalId": 90100006,
        "SignalName": "Run Status",
        "SignalValue": 4.0,
        "SignalMeaning": "Charging",
        "SignalUnit": "",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100007": {
        "SignalId": 90100007,
        "SignalName": "Fault code",
        "SignalValue": 0.0,
        "SignalMeaning": "Normal",
        "SignalUnit": "",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100009": {
        "SignalId": 90100009,
        "SignalName": "Reason for stopping charging",
        "SignalValue": 144.0,
        "SignalMeaning": "Pulling out charger",
        "SignalUnit": "",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100200": {
        "SignalId": 90100200,
        "SignalName": "Leakage current",
        "SignalValue": 1.7,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100204": {
        "SignalId": 90100204,
        "SignalName": "Max current",
        "SignalValue": 32.0,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100205": {
        "SignalId": 90100205,
        "SignalName": "Set current",
        "SignalValue": 32.0,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100206": {
        "SignalId": 90100206,
        "SignalName": "Current",
        "SignalValue": 30.3,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100207": {
        "SignalId": 90100207,
        "SignalName": "PWM duty cycle",
        "SignalValue": 534.4,
        "SignalMeaning": None,
        "SignalUnit": "%",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100208": {
        "SignalId": 90100208,
        "SignalName": "CP voltage",
        "SignalValue": 5.9,
        "SignalMeaning": None,
        "SignalUnit": "V",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100209": {
        "SignalId": 90100209,
        "SignalName": "This time charged duration",
        "SignalValue": 29.0,
        "SignalMeaning": None,
        "SignalUnit": "min",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100210": {
        "SignalId": 90100210,
        "SignalName": "Plug temperature",
        "SignalValue": 27.0,
        "SignalMeaning": None,
        "SignalUnit": "℃",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100211": {
        "SignalId": 90100211,
        "SignalName": "Male Connector temperature",
        "SignalValue": 34.0,
        "SignalMeaning": None,
        "SignalUnit": "℃",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100214": {
        "SignalId": 90100214,
        "SignalName": "CT_Ia",
        "SignalValue": 0.0,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100215": {
        "SignalId": 90100215,
        "SignalName": "CT_Ib",
        "SignalValue": 0.0,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100216": {
        "SignalId": 90100216,
        "SignalName": "CT_Ic",
        "SignalValue": 0.0,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100300": {
        "SignalId": 90100300,
        "SignalName": "Voltage",
        "SignalValue": 250.3,
        "SignalMeaning": None,
        "SignalUnit": "V",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100301": {
        "SignalId": 90100301,
        "SignalName": "Voltage B",
        "SignalValue": 0.0,
        "SignalMeaning": None,
        "SignalUnit": "V",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100302": {
        "SignalId": 90100302,
        "SignalName": "Voltage C",
        "SignalValue": 0.0,
        "SignalMeaning": None,
        "SignalUnit": "V",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100303": {
        "SignalId": 90100303,
        "SignalName": "Current",
        "SignalValue": 30.3,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100304": {
        "SignalId": 90100304,
        "SignalName": "Current B",
        "SignalValue": 0.0,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100305": {
        "SignalId": 90100305,
        "SignalName": "Current C",
        "SignalValue": 0.0,
        "SignalMeaning": None,
        "SignalUnit": "A",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100306": {
        "SignalId": 90100306,
        "SignalName": "Power",
        "SignalValue": 7.6,
        "SignalMeaning": None,
        "SignalUnit": "kW",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100217": {
        "SignalId": 90100217,
        "SignalName": "This time charged elec",
        "SignalValue": 3.6,
        "SignalMeaning": None,
        "SignalUnit": "kWh",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
    "90100201": {
        "SignalId": 90100201,
        "SignalName": "Start charging time",
        "SignalValue": 0.0,
        "SignalMeaning": "2026-04-25 14:32:45",
        "SignalUnit": "",
        "BlockType": 0,
        "UpdateTime": "2026-04-25 15:01:52",
    },
}

__login_data: dict[str, t.Any] = {
    "LoginType": 2,
    "Token": "testing-token-1234567890abcdef",
    "CompanyType": 0,
    "CompanyCode": "PionPower",
    "GenerateTime": "2026-05-03 06:20:38",
    "LastVisitTime": "2026-05-03 06:20:38",
    "Language": "en-us",
    "Id": 0,
    "UserLoginId": "user@example.com",
    "UserName": "Example User",
    "Email": "user@example.com",
    "EmailStatus": 0,
    "RoleId": "12345678901234567890123456789012",
}

__station_one: dict[str, t.Any] = {
    "StationCode": generate_random_string(18),
    "StationName": "Household Name",
    "StationType": 4,
    "IsDefaultStation": True,
    "AuthType": 1,
    "MemberCount": 0,
    "DeviceCount": 0,
    "Country": "",
    "Province": "",
    "City": "",
    "Area": "",
}

__station_two: dict[str, t.Any] = {
    "StationCode": generate_random_string(18),
    "StationName": "Workshop",
    "StationType": 4,
    "IsDefaultStation": False,
    "AuthType": 1,
    "MemberCount": 0,
    "DeviceCount": 0,
    "Country": "",
    "Province": "",
    "City": "",
    "Area": "",
}

one_device: dict[str, dict[str, t.Any]] = {
    "login": {
        "Code": 1,
        "Msg": "Success",
        "Data": __login_data,
    },
    "get_device": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_one,
    },
    "get_device_list": {
        "Code": 1,
        "Msg": "Success",
        "Data": [__device_one],
    },
    "get_device_stats": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_stats,
    },
    "get_realtime_data_by_device_code": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_data,
    },
    "get_station_list": {
        "Code": 1,
        "Msg": "Success",
        "Data": [__station_one],
    },
}

two_devices: dict[str, dict[str, t.Any]] = {
    "login": {
        "Code": 1,
        "Msg": "Success",
        "Data": __login_data,
    },
    "get_device": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_one,
    },
    "get_device_list": {
        "Code": 1,
        "Msg": "Success",
        "Data": [__device_one, __device_two],
    },
    "get_device_stats": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_stats,
    },
    "get_realtime_data_by_device_code": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_data,
    },
    "get_station_list": {
        "Code": 1,
        "Msg": "Success",
        "Data": [__station_one],
    },
}

two_stations: dict[str, dict[str, t.Any]] = {
    "login": {
        "Code": 1,
        "Msg": "Success",
        "Data": __login_data,
    },
    "get_device": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_one,
    },
    "get_device_list": {
        "Code": 1,
        "Msg": "Success",
        "Data": [__device_one, __device_two],
    },
    "get_device_stats": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_stats,
    },
    "get_realtime_data_by_device_code": {
        "Code": 1,
        "Msg": "Success",
        "Data": __device_data,
    },
    "get_station_list": {
        "Code": 1,
        "Msg": "Success",
        "Data": [__station_one, __station_two],
    },
}
